experiment_name: 'ACDC + SCD Pretraining (New: SCD)'

data_params:
  acdc:
    include: True
    tagged: True
    only_myo: True
  dmd:
    include: False
  scd:
    include: True
    tagged: True
  self_supervised: False
  semi_supervised: False
  base_model: 

train_val_split: .75
batch_size: 8

pretrained_model: 
trained_model: 'data/06_models/model_cine_tag_only_myo_v4.pt'
train_params:
  learning_rate: .001
  weight_decay: .00001
  momentum: .9
  epochs: 75
