experiment:
  name: 'Pretraining2 SegResNetVAE with cine data'

data:
  acdc:
    include: True
  dmd:
    include: False
  scd:
    include: True
  mnm:
    include: True
  train_val_split: .75
  batch_size: 8

transformation:
  perform: False
  generator_model: data/06_models/netG_A2B.pth
  batch_size: 16

training:
  learning_rate: 0.01
  weight_decay: .00001
  epochs: 100
  self_supervised: False
  semi_supervised: False
  ss_model: 
  pretrain_model: 'data/06_models/model_cycleGAN_cine2tag_v3.pt'
  checkpoint: 'data/06_models/model_cycleGAN_cine2tag_v4.pt'
