experiment:
  name: 'Finetuning UNet w/ tagged data and middle SDL'

data:
  acdc:
    include: True
  scd:
    include: True
  mnm:
    include: True
  train_val_split: .75
  batch_size: 128

transformation:
  perform: True
  generator_model: data/06_models/netG_A2B.pth
  batch_size: 16

training:
  model_type: 'UNet'
  learning_rate: 0.005
  weight_decay: .0001
  gamma: 0.05
  epochs: 200
  pretrain_model: data/06_models/model_cine_v7/E085.pt
  checkpoint: 'data/06_models/model_cine_v7_tag_v4.pt'

evaluation:
  model_type: 'SegResNetVAE'
  load_model: data/06_models/model_cine_v6_tag_v1.pt
  save_path: data/08_reporting/model_cine_v6_tag_v1