experiment:
  name: 'Pretraining DynUNet w/ cine images'

data:
  acdc:
    include: True
  scd:
    include: True
  mnm:
    include: True
  train_val_split: .75
  batch_size: 100

transformation:
  perform: False
  generator_model: data/06_models/netG_A2B.pth
  batch_size: 16

training:
  model_type: 'DynUNet'
  learning_rate: .005
  weight_decay: .0001
  gamma: 0.
  epochs: 200
  pretrain_model: 
  checkpoint: 'data/06_models/model_cine_v8.pt'

evaluation:
#   model_type: 'SegResNetVAE'
#   load_model: data/06_models/model_cine_v6_tag_v1.pt
#   save_path: data/08_reporting/model_cine_v6_tag_v1