pretrained_model: 'data/06_models/model_cine_tag_v1_sd.pt'
trained_model: 'data/06_models/model_cine_tag_vINF_sd.pt'
train_params:
  learning_rate: .01
  weight_decay: .001
  momentum: .9
  epochs: 75
